USE ShopSmart_Retail_Analytics;

#What is the total revenue generated by the company?
select round(sum(sales),2) as total_revenue
from fact_sales;

#What is the total profit earned by the company
select round(sum(profit),2)  as total_profit
from fact_sales;

#How many product units were sold?
select sum(quantity) as product_unit
from fact_sales;


#What is the average revenue generated per order?
#Note as the order is is not unique, for each order, sowe can calculate average revenue per transaction
select round(avg(sales)) as avg_revenue_transaction
from fact_sales;

#On average, how much profit does one sales transaction generate?
select round(avg(profit),2) as on_avg_profit
from fact_sales;

#What percentage of total revenue becomes profit?


#What is the average discount offered across all sales?
select round(avg(discount),2) as avg_discount
from fact_sales;

#What is the average shipping cost per sales transaction?
select round(avg(shipping_cost)) as avg_shipping_cost
from fact_sales;

#What is the highest sales value recorded in a single transaction?
select round(max(sales),2) as highes_sales_transaction
from fact_sales;

#What is the highest profit earned from a single transaction?
select round(max(profit),2) as highes_profit
from fact_sales;

