#Regional Analysis
use ShopSmart_Retail_Analytics;

#Which market generates the highest revenue?
with market_revenue as
(select l.market,
round(sum(sales),2) as total_revenue,
round(sum(profit),2) as total_profit
from location l
inner join fact_sales f
using(location_id)
group by l.market)
select market,
total_revenue,
total_profit,
round((total_revenue/
           (select sum(total_revenue) from market_revenue))*100,2) as revenue_percent
from market_revenue
order by total_revenue desc;

#Which region contributes the highest revenue?
select l.region, round(sum(sales),2) as total_revenue,
round(sum(profit),2) as total_profit
from location l
inner join fact_sales f
using(location_id)
group by l.region
order by total_revenue desc;

#Which 10 countries generate the highest revenue
select l.country, round(sum(sales),2) as total_revenue,
round(sum(profit),2) as total_profit
from location l
inner join fact_sales f
using(location_id)
group by l.country
order by total_revenue desc
limit 10;

#Which 10 states generate the highest revenue?
select l.state, round(sum(sales),2) as total_revenue,
round(sum(profit),2) as total_profit
from location l
inner join fact_sales f
using(location_id)
group by l.state
order by total_revenue desc
limit 10;

#Which 10 cities generate the highest revenue?
select l.city, round(sum(sales),2) as total_revenue,
round(sum(profit),2) as total_profit
from location l
inner join fact_sales f
using(location_id)
group by l.city
order by total_revenue desc
limit 10;

#Which 10 countries generate the lowest profit?
select l.country, 
round(sum(profit),2) as total_profit
from location l
inner join fact_sales f
using(location_id)
group by l.country
order by total_profit asc
limit 10;

#What is the average revenue generated by each country?
select l.country,
round(avg(sales),2) as avg_transaction_revenue
from location l
inner join fact_sales f
using(location_id)
group by l.country
order by avg_transaction_revenue desc
limit 10;

#Rank markets based on total revenue.
with market_revenue as
(select l.market, sum(sales) as total_revenue
      from location l
      inner join fact_sales f 
      using(location_id)
      group by l.market)
select market, total_revenue,
	  dense_rank() over(order by total_revenue desc) as revenue_rnk
from market_revenue;

#Identify regions whose total revenue is above the average regional revenue.
with region_revenue as 
    (select l.region, 
    sum(f.sales) as total_revenue
    from location l
    inner join fact_sales f
    using(location_id)
    group by l.region)
select region, total_revenue
from region_revenue
where total_revenue >(select avg(total_revenue)
                       from region_revenue)
order by total_revenue desc;


#What percentage of the company's total revenue comes from each market?
with market_revenue as 
     (
     select l.market, 
     round(sum(sales),2) as total_revenue
     from location l
     inner join fact_sales f
     using(location_id)
     group by l.market)
select market, total_revenue,
round((total_revenue/ 
       (select sum(total_revenue) from market_revenue))*100,2) as market_perc_contribution
from market_revenue
order by market_perc_contribution desc;



