#Shipping Analysis
use ShopSmart_Retail_Analytics;

#Which shipping mode generates the highest revenue?
select o.ship_mode, round(sum(sales),2) as total_revenue,
       round(sum(profit),2) as total_profit,
       count(distinct order_id) as order_count
from orders o
inner join fact_sales f
using(order_id)
group by o.ship_mode
order by total_revenue desc;

#Which shipping mode has the highest average shipping cost?
select o.ship_mode, 
 round(avg(f.shipping_cost),2) as avg_ship_cost
from orders o
inner join fact_sales f
using(order_id)
group by o.ship_mode
order by avg_ship_cost desc;

#What is the average delivery time (in days) for each shipping mode?
select o.ship_mode,
round(avg(datediff(f.ship_date,o.order_date)),2) as avg_delivery_days
from fact_sales f
inner join orders o
using(order_id)
group by o.ship_mode;

#Which shipping mode delivers orders the fastest on average?
select o.ship_mode,avg(datediff(f.ship_date,o.order_date)) as avg_delivery_days
from fact_sales f
inner join orders o
using(order_id)
group by o.ship_mode
order by avg_delivery_days asc;

#Which shipping mode is used most often?
select o.ship_mode, count(distinct order_id) as count_orders
from fact_sales f
inner join orders o
using(order_id)
group by o.ship_mode
order by count_orders desc;

#Which shipping mode generates the highest revenue relative to its shipping cost?
with ship_measures as (
  select o.ship_mode, sum(sales) as total_revenue,
         sum(f.shipping_cost) as total_shipcost
         from orders o
         inner join fact_sales f 
         using(order_id)
         group by o.ship_mode)
select ship_mode, round(total_revenue) as total_revenue,
round(total_shipcost) as total_shipcost,
round((total_revenue/total_shipcost),2) as cost_ratio
from ship_measures
order by cost_ratio desc;
 
#Which 10 transactions had the highest shipping cost?
select f.transaction_id, f.order_id,c.customer_name,f.ship_mode,
round(f.shipping_cost) as total_shipping_cost
from fact_sales f 
inner join customer c
using(customer_id)
group by f.transaction_id, f.order_id,c.customer_name,f.ship_mode
order by total_shipping_cost desc
limit 10;

#What percentage of total shipping cost comes from each shipping mode?
with ship_measure as 
( select ship_mode,
         sum(shipping_cost) as total_ship_cost
         from fact_sales
         group by ship_mode
         )
select ship_mode,
       round(total_ship_cost) as total_cost,
       round((total_ship_cost/(select sum(total_ship_cost)
       from ship_measure))*100,2) as percentage
       from ship_measure;


#Compare revenue generated by fast shipping modes versus slower shipping modes.
select case 
        when ship_mode in ("Same Day","First Class")  then "Fast_Shipping"
        else "slower_shipping"
        end as shipping_category,
        round(sum(sales),2) as total_revenue,
        round(sum(profit),2) as total_profit
        from fact_sales
        group by shipping_category;
        
#Rank shipping modes based on total revenue.
with ship_modes as 
(select ship_mode, 
		sum(sales) as total_revenue
        from fact_sales
        group by ship_mode
        )
select ship_mode, round(total_revenue) as total_revenue,
       dense_rank() over(order by total_revenue desc) as rnk
       from ship_modes
       order by total_revenue desc;

        













